# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkusdb

# Hibernate configuration
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# Flyway migrations
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
quarkus.flyway.repair-at-start=true

# HTTP configuration
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# Security configuration
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.password, p.name FROM users u JOIN user_profiles p ON u.profile_id = p.id WHERE u.email = ?
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.iteration-count-index=-1
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.salt-index=-1
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=2
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups

# Form-based authentication
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/login
quarkus.http.auth.form.error-page=/login?error=true
quarkus.http.auth.form.landing-page=/users
quarkus.http.auth.permission.login.paths=/login
quarkus.http.auth.permission.login.methods=GET
quarkus.http.auth.permission.login.policy=permit
quarkus.http.auth.session.encryption-key=ikuFOEQQVWrevWrFMWE7swnLHZaNFVnMimKqhANB1DI=
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated
quarkus.http.auth.permission.default.auth-mechanism=form

# Audit logging
quarkus.log.category."com.robsonbs.filter".level=DEBUG
